services:
  minio:
    image: minio/minio:RELEASE.2023-04-13T03-08-07Z
    container_name: minio
    ports:
      # api 端口 (将主机的 9000 端口映射到容器的 9000 端口)
      - "9000:9000"
      # 控制台端口 (将主机的 9001 端口映射到容器的 9001 端口)
      - "9001:9001"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 管理后台用户名
      MINIO_ROOT_USER: ruoyi
      # 管理后台密码，最小8个字符
      MINIO_ROOT_PASSWORD: ruoyi123
      # https需要指定域名
      #MINIO_SERVER_URL: "https://xxx.com:9000"
      #MINIO_BROWSER_REDIRECT_URL: "https://xxx.com:9001"
      # 开启压缩 on 开启 off 关闭
      MINIO_COMPRESS: "off"
      # 扩展名 .pdf,.doc 为空 所有类型均压缩
      MINIO_COMPRESS_EXTENSIONS: ""
      # mime 类型 application/pdf 为空 所有类型均压缩
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      # 映射当前目录下的data目录至容器内/data目录
      - /Users/apple/code/ruoyi-plus/minio/data:/data
      # 映射配置目录
      - /Users/apple/code/ruoyi-plus/minio/config:/root/.minio/
    command: server --address ':9000' --console-address ':9001' /data
    # privileged: true  # <-- 已移除，通常不需要
    # network_mode: "host" # <-- 这是关键，必须移除或注释掉
