--- # 临时文件存储位置 避免临时文件被系统清理报错
spring.servlet.multipart.location: /ruoyi/server/temp

--- # 监控中心配置
spring.boot.admin.client:
  # 增加客户端开关
  enabled: true
  url: http://localhost:9090/admin
  instance:
    service-host-type: IP
    metadata:
      username: ${spring.boot.admin.client.username}
      userpassword: ${spring.boot.admin.client.password}
  username: @monitor.username@
  password: @monitor.password@

--- # snail-job 配置
snail-job:
  enabled: true
  # 需要在 SnailJob 后台组管理创建对应名称的组,然后创建任务的时候选择对应的组,才能正确分派任务
  group: "ruoyi_group"
  # SnailJob 接入验证令牌 详见 script/sql/ry_job.sql `sj_group_config`表
  token: "SJ_cKqBTPzCsWA3VyuCfFoccmuIEGXjr5KT"
  server:
    host: 127.0.0.1
    port: 17888
  # 命名空间UUID 详见 script/sql/ry_job.sql `sj_namespace`表`unique_id`字段
  namespace: ${spring.profiles.active}
  # 随主应用端口漂移
  port: 2${server.port}
  # 客户端ip指定
  host:
  # RPC类型: netty, grpc
  rpc-type: grpc

--- # 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: false
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
          url: jdbc:mysql://localhost:3306/football?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
          username: root
          password: 3!MakvA3iTPDfJpBR#
      #        # 从库数据源
      #        slave:
      #          lazy: true
      #          type: ${spring.datasource.type}
      #          driverClassName: com.mysql.cj.jdbc.Driver
      #          url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
      #          username:
      #          password:
      #        oracle:
      #          type: ${spring.datasource.type}
      #          driverClassName: oracle.jdbc.OracleDriver
      #          url: jdbc:oracle:thin:@//localhost:1521/XE
      #          username: ROOT
      #          password: root
      #        postgres:
      #          type: ${spring.datasource.type}
      #          driverClassName: org.postgresql.Driver
      #          url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=true
      #          username: root
      #          password: root
      #        sqlserver:
      #          type: ${spring.datasource.type}
      #          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      #          url: jdbc:sqlserver://localhost:1433;DatabaseName=tempdb;SelectMethod=cursor;encrypt=false;rewriteBatchedStatements=true
      #          username: SA
      #          password: root
      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 30000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 600000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 1800000
        # 多久检查一次连接的活性
        keepaliveTime: 30000

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring.data:
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # redis 密码必须配置
    password: 3!MakvA3iTPDfJpBR#
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl.enabled: false

# redisson 配置
redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 16
  # Netty线程池数量
  nettyThreads: 32
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${ruoyi.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 32
    # 连接池大小
    connectionPoolSize: 64
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

--- # mail 邮件发送
mail:
  enabled: false
  host: smtp.163.com
  port: 465
  # 是否需要用户名密码验证
  auth: true
  # 发送方，遵循RFC-822标准
  from: xxx@163.com
  # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
  user: xxx@163.com
  # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
  pass: xxxxxxxxxx
  # 使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。
  starttlsEnable: true
  # 使用SSL安全连接
  sslEnable: true
  # SMTP超时时长，单位毫秒，缺省值不超时
  timeout: 0
  # Socket连接超时值，单位毫秒，缺省值不超时
  connectionTimeout: 0

--- # sms 短信 支持 阿里云 腾讯云 云片 等等各式各样的短信服务商
# https://sms4j.com/doc3/ 差异配置文档地址 支持单厂商多配置，可以配置多个同时使用
sms:
  # 配置源类型用于标定配置来源(interface,yaml)
  config-type: yaml
  # 用于标定yml中的配置是否开启短信拦截，接口配置不受此限制
  restricted: true
  # 短信拦截限制单手机号每分钟最大发送，只对开启了拦截的配置有效
  minute-max: 1
  # 短信拦截限制单手机号每日最大发送量，只对开启了拦截的配置有效
  account-max: 30
  # 以下配置来自于 org.dromara.sms4j.provider.config.BaseConfig类中
  blends:
    # 唯一ID 用于发送短信寻找具体配置 随便定义别用中文即可
    # 可以同时存在两个相同厂商 例如: ali1 ali2 两个不同的阿里短信账号 也可用于区分租户
    config1:
      # 框架定义的厂商名称标识，标定此配置是哪个厂商，详细请看厂商标识介绍部分
      supplier: alibaba
      # 有些称为accessKey有些称之为apiKey，也有称为sdkKey或者appId。
      access-key-id: 您的accessKey
      # 称为accessSecret有些称之为apiSecret
      access-key-secret: 您的accessKeySecret
      signature: 您的短信签名
      sdk-app-id: 您的sdkAppId
    config2:
      # 厂商标识，标定此配置是哪个厂商，详细请看厂商标识介绍部分
      supplier: tencent
      access-key-id: 您的accessKey
      access-key-secret: 您的accessKeySecret
      signature: 您的短信签名
      sdk-app-id: 您的sdkAppId


--- # 三方授权
justauth:
  # 前端外网访问地址
  address: http://localhost:80
  type:
    maxkey:
      # maxkey 服务器地址
      # 注意 如下均配置均不需要修改 maxkey 已经内置好了数据
      server-url: http://sso.maxkey.top
      client-id: 876892492581044224
      client-secret: x1Y5MTMwNzIwMjMxNTM4NDc3Mzche8
      redirect-uri: ${justauth.address}/social-callback?source=maxkey
    topiam:
      # topiam 服务器地址
      server-url: http://127.0.0.1:1989/api/v1/authorize/y0q************spq***********8ol
      client-id: 449c4*********937************759
      client-secret: ac7***********1e0************28d
      redirect-uri: ${justauth.address}/social-callback?source=topiam
      scopes: [ openid, email, phone, profile ]
    qq:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=qq
      union-id: false
    weibo:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=weibo
    gitee:
      client-id: 91436b7940090d09c72c7daf85b959cfd5f215d67eea73acbf61b6b590751a98
      client-secret: 02c6fcfd70342980cd8dd2f2c06c1a350645d76c754d7a264c4e125f9ba915ac
      redirect-uri: ${justauth.address}/social-callback?source=gitee
    dingtalk:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=dingtalk
    baidu:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=baidu
    csdn:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=csdn
    coding:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=coding
      coding-group-name: xx
    oschina:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=oschina
    alipay_wallet:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=alipay_wallet
      alipay-public-key: MIIB**************DAQAB
    wechat_open:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=wechat_open
    wechat_mp:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=wechat_mp
    wechat_enterprise:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=wechat_enterprise
      agent-id: 1000002
    gitlab:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=gitlab

# api接口加密
api-decrypt:
  # 是否开启全局接口加密
  enabled: true
  # AES 加密头标识
  headerFlag: encrypt-key
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnj7ardHipMR5ivhjSemFQ32osTNX81Z/SLup5dImGhhUQOYxii7aeL09+KuySgI7G6daoTR0hLsWPvkVO50PEJdGq/GZ0pmOFj39CxZZwj0EKnZ0V/WeqGwHSdSvmoCmPvUT3JBsQMd4NoAngEJHbZ3B8ADfM8rGbqup6rS9ZULhxy98ukMqUqWSwQ4mL9U8dXAHJm2J+XskAxLmJLY//ss0cktaA+4Ee/mvz/TyzxMNT/wGt+tzIZFJO9p7yL0Km8739V8Y4o+/f6Si032Td6U9VuOJfmeYmDyjeHhdBX9qj5+eAIRDKsjfGxWeUObMS35AeFFfZGB0F06EpizpwwIDAQAB
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDATcz4p+3Eo65j+KgYLoqlPYtY7BlM80636ekGHXd9P4cbj7EGGHHB/4hnSSb5pF7BRhSWGh/8tQKjaHloqMbAaOSDhERBbRe9py0UI8UibeVbJhLhmu85BflqpIeE9DpOzRID3SI4+FGTNMBBygHX1m/Oe+BVPMeaKCuFaZCBuH8TdKDjzpOMqfftxhYuGP1uD3hSZzJEx9h3Yr7SvozuxxaVdhnu2cN/nO94CXqzodRZ3DK4OxNeYKGMNpxjAdi2u9a81JuBzc4HE8PJuzJprc+HAwuDOy/nZZTx8ih+6c7FM+j8yssk5raBtGRXVeNmnUVEIH1cHWWwes2MvwmlAgMBAAECggEAIQZ7eAym6clObr7KZ3S+vMgIAVpyseNrFmymZzVySuE5G8OenDRgfPecflhyyBaxazHU4T5VVfnkHRoZF588mtioveleK3pHxHtMY5QNC++hnvi372TDRqC/B9B/sZab2OKhAGbetLf4knZRujqt/FpIU0a07Q6GHPRfHQdXGN/Ah/tgT76g97EQcA9VA0CnP2e6cY1wril2QCl7sSkhFF97acdotajEe31m+8MEjveQwPwcjJYdVI1UGRFUlXt1KzTVDz8NDdMKVjt6/G2TqDGSl2bT1Z5D2FFCY3O0qP87xqfkLZGFzaxfk3D3fPS/XLvZCeePEr4LdBL6RzuK1QKBgQD/CClP1hf54+Cwp4XYeZv5St6aXb0//r+DPgQ+xluxdNJCzzSXMWSTdj4NFdghsKrJFknlHxwGbhcecL8FDVN9UoFYmeLkZC0JLpZSVFyyIBZraF+WddhIW8lILiULWG9BTLPhiGcN2/suOCa4CcDr7z70Wj9CyGLjVKXyuD/b+wKBgQDBCK462exasVCoB92MARpETRDYSSShSTyGOfGe/YPDt/4/rEML2Rr52eF6V5fmTn/0h1siHZ8EsIoYLAQe1WVUTXXUXNoB+U0nKwPABfjN5nBRvfAmRlDhKdNT6doqzekOHxhnltVA4rKvkqrs4Q7aLpQF80KUb/4mU/Ok5VUe3wKBgQCkcovI+iFdtg4FexA4ZTopBpkBat6EbGzrYMr1+4vWoqCOCfQ8ZdIXsBAU+ffyyWtm3ONrRaMZllV8AHF7/XrPfasACcKfSOUtXYf6sIFRLpWmTpgMehKrndvtmiuy5CRhM+dtzzm8WxPdWsHEvC1VNWEfyS2vj20Mb2HOX/Z1jwKBgQCx6wNTwQrFaMtTpLRB175TF8kf4QK/GdaMTRn0Fex917ejDm5ZnEjt4zGc5uFd6Bqt0phf8HdiBimyL9e4Z63WrvKcwtw5l4PSRyZUtexmMzBxVyTi0kq3zio3HML2UwWs+2IuEGsMPCbABuo+HQ3ocagDd/x0/mh9AUH/SVVUdwKBgGpfZm3bQjHq1l3Ng/qtbg4sW99IwPhVRKEuEFLn/CR2lPxI/mt47xeDq8o2erqLXkE1V1JP93jMGbolnCJVG5/RcbhoSJA5eEvJDR7W2w22cEEgO7xsTVl8n78P0/05aJisbUl3W2e4EqHep/4QkTF6/lnwvhfeMotVsl2RFD5/


bscscan:
  api-url: "https://api.etherscan.io/v2/api"
  api-key: "U6Q93R3G9GABX9HDSQHXV915UBVJ7FH5NZ"
  usdt-contract-address: "0x55d398326f99059fF775485246999027B3197955"
  chain-id: 56
  wssUrl: wss://bsc-ws.nodereal.io:3659
